version: "2"

services:
  vscode:
    image: codercom/code-server
    command: --allow-http --port=8080
    container_name: vscode-server
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:vscode.domain"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
    volumes:
      - data:/home/coder/project

networks:
  web:
    external: true

volumes:
  data: 
